services:
  - type: web
    name: 14-manioc-investment-web
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
